### ISSUE TITLE
Provide better output for -h

### ISSUE THREAD

**Issue by TheSnoozer** [joodicator/mc-dev-data#1]
Hi,
sorry to also bother this project of yours :-P
I started to actually use the python tool instead of just looking at the generated page :P

One thing I noticed is that the help doesn't really provide me any information on what the arguments are doing or should do. I'm pretty confident that you added each argument for a reason, but after a short testing I can't find any real differences in the outcome.

I think a short documentation might explain when and where a certain argument would help and how it effects the generated result.

Just to share my initial idea:
One easy quick fix of achieving such documentation is simply to provide all functions that are listed in the help (or in other words all the functions that are decorated with ``from_page_func``) with a docstring.

E.g.
```python
@from_page(get_soup)
def first_heading(soup):
    """A brief explanation what the command line argument would do to the output"""
    return soup.find(id='firstHeading').text.strip() 
```

Since you are collecting the functions by the ``from_page_func`` name the decorator would need to "inherit" the original doc (e.g. ``from_page_func.__doc__ = func.__doc__``).

The collection of method names then simply could be adjusted to create a pair of argument-name and documented purpose (e.g.
```python
    nullary_args = sorted(['-r%s' % key, val.__doc__] for key, val in globals().items() if
                   inspect.isfunction(val) and val.__name__ == 'from_page_func')
.....
    for arg, doc in nullary_args:
            print('               [%s] - %s' % (arg, doc), file=sys.stderr)
....
    if all(not arg.startswith(a) for a in unary_args) and arg not in [arg for arg,_ in nullary_args]:
...
```

WDYT?
If you would explain what the individual arguments are supposed to to, I'd be happy to attempt to create a MR ;-)

**Comment by joodicator** [comment]
@TheSnoozer Admittedly, this started out as a quick hack, which I wasn't expecting anyone else to read, but it grew into something larger and is now quite badly organised and undocumented. I've taken your suggestion and added (in 8ea06c2) better documentation about the command-line arguments, as well as more comments in the code in general. At present, this is the output of `main.py --help`:
```
Usage: main.py [-h|--help] [RFLAGS...]

This script generates and prints to stdout the contents of index.htm.
To save time, much intermediate data is saved under the "func-cache" directory.
When the script or source data are changed, RFLAGS may be given to tell which
data need to be recalculated. Alternatively, the entire func-cache may be
deleted, to recalculate everything.

The possible RFLAGS are:
   -rversion_packet_ids
      Recalculate the packet ID matrix. Give if the version_urls dict
      or the code of version_packet_ids() have been changed.
   -rpycraft_packet_classes
      Recalculate pyCraft data. Give if the local pyCraft version
      or the code of pycraft_packet_classes() have changed.
   -rfirst_heading
      Recalculate first_heading(). Give if its code has changed.
   -rpre_packets
      Recalculate pre_packets(). Give if its code has changed.
   -rpre_versions
      Recalculate pre_versions(). Give if its code has changed.
   -rrel_packets
      Recalculate rel_packets(). Give if its code has changed.
   -rrel_version
      Recalculate rel_version(). Give if its code has changed.
   --r-min-proto=VER
      Recalculate only for protocol versions >= this value.
   --r-max-proto=VER
      Recalculate only for protocol versions <= this value.
```

As you can see, `-rpycraft_packet_classes` and `-rversion_packet_ids` are the two arguments that would most frequently need to be used. Let me know if anything is still unclear after this!

**Comment by TheSnoozer** [comment]
That looks awesome and should do the job!
Thank you for doing that!
As a side note almost all of my projects start out as a quick hack....;-)
